companies = [
    "Amira Learning",
    "Barclays",
    "Bertelsmann",
    "Boston Consulting Group",
    "Bright Horizons",
    "Cengage",
    "Chan Zuckerberg Initiative",
    "Chegg",
    "CompTIA",
    "Course Hero",
    "Coursera",
    "Duolingo",
    "Edmentum",
    "Education Week",
    "Emeritus",
    "Explorance",
    "Frontline Education",
    "Goldman Sachs",
    "Google Cloud",
    "Handshake",
    "JFF",
    "Kaplan",
    "Macquarie Capital",
    "McGraw Hill",
    "McKinsey",
    "Microsoft",
    "Morgan Stanley",
    "Pearson",
    "Prosus",
    "Renaissance",
    "Scholastic Corporation",
    "Skillsoft",
    "The Princeton Review/Tutor.com",
    "Walton Family Foundation",
    "WGU",
    "Wiley",
    "William Blair",
    "Zoom"
]

companies_list = ",".join(companies)

education_terms = ["education", "edtech", "school", "university", "learning",
                   "student", "teacher", "study", "professor", "class",
                   "skill", "course", "college", "tutor"]